SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS SA SALT '630a6d29019b5635' HASH 'd02d8a4c16603b56be3ef934b2fd2684836be2efb9da70a4f915d6411aac799f' ADMIN;            
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2069E3C1_5629_4793_99CA_48DBE02FF767 START WITH 1 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2DD5252D_AA42_4D16_AEAE_08F481A3AE6E START WITH 3 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A8F008EC_3A0B_4618_A31A_2B637784AA73 START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B29346B4_5AEC_41EF_8D0D_A224D2928FCC START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E4A3841B_5849_48E1_8CF3_DA4EE76CFDC5 START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_91EA0340_7F7F_4044_92E8_9ADC16B387B4 START WITH 2 BELONGS_TO_TABLE;     
CREATE MEMORY TABLE PUBLIC.CENTRE(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_E4A3841B_5849_48E1_8CF3_DA4EE76CFDC5) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_E4A3841B_5849_48E1_8CF3_DA4EE76CFDC5,
    ADRESSE VARCHAR(255),
    NB_ESSAIS INTEGER NOT NULL,
    NB_SUCCES INTEGER NOT NULL,
    NOM VARCHAR(255),
    VILLE VARCHAR(255)
);
ALTER TABLE PUBLIC.CENTRE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CENTRE;   
INSERT INTO PUBLIC.CENTRE(ID, ADRESSE, NB_ESSAIS, NB_SUCCES, NOM, VILLE) VALUES
(1, '45 rue Dicaprio', 0, 0, 'Pitt', 'Smith'),
(2, '20 avenue Johnson', 10, 8, 'Dwayne', 'Toulouse'),
(3, '10 rue des troubadours', 2, 2, 'Mirage', 'Plaisir'),
(4, '1 rue du ballon rouge', 21, 15, 'Orangeade', 'Draguignan');  
CREATE MEMORY TABLE PUBLIC.DONNEUR(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_91EA0340_7F7F_4044_92E8_9ADC16B387B4) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_91EA0340_7F7F_4044_92E8_9ADC16B387B4,
    AGE INTEGER NOT NULL,
    ANTECEDENTS INTEGER,
    ATTENTE BOOLEAN NOT NULL,
    CHEVEUX INTEGER,
    DISPONIBILITE BOOLEAN NOT NULL,
    LOISIRS INTEGER,
    NOM VARCHAR(255),
    PEAU INTEGER,
    POIDS INTEGER NOT NULL,
    PRENOM VARCHAR(255),
    SEXE BOOLEAN NOT NULL,
    SIGNALE BOOLEAN NOT NULL,
    TAILLE INTEGER NOT NULL,
    YEUX INTEGER,
    OWNER_ID INTEGER
);             
ALTER TABLE PUBLIC.DONNEUR ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.DONNEUR;  
INSERT INTO PUBLIC.DONNEUR(ID, AGE, ANTECEDENTS, ATTENTE, CHEVEUX, DISPONIBILITE, LOISIRS, NOM, PEAU, POIDS, PRENOM, SEXE, SIGNALE, TAILLE, YEUX, OWNER_ID) VALUES
(1, 72, 2, TRUE, 2, TRUE, 2, 'Birkin', 1, 70, 'Jane', TRUE, FALSE, 173, 0, NULL);                  
CREATE MEMORY TABLE PUBLIC.MEDECIN(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A8F008EC_3A0B_4618_A31A_2B637784AA73) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_A8F008EC_3A0B_4618_A31A_2B637784AA73,
    NOM VARCHAR(255),
    SEXE BOOLEAN NOT NULL,
    SPECIALISATION INTEGER,
    OWNER_ID INTEGER
);    
ALTER TABLE PUBLIC.MEDECIN ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.MEDECIN;  
INSERT INTO PUBLIC.MEDECIN(ID, NOM, SEXE, SPECIALISATION, OWNER_ID) VALUES
(1, 'Stark', FALSE, 0, 1);          
CREATE MEMORY TABLE PUBLIC.RDV(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2069E3C1_5629_4793_99CA_48DBE02FF767) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2069E3C1_5629_4793_99CA_48DBE02FF767,
    HEURE INTEGER NOT NULL,
    OWNER_ID INTEGER
);         
ALTER TABLE PUBLIC.RDV ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RDV;      
CREATE MEMORY TABLE PUBLIC.RECEVEUR(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B29346B4_5AEC_41EF_8D0D_A224D2928FCC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_B29346B4_5AEC_41EF_8D0D_A224D2928FCC,
    AGE INTEGER NOT NULL,
    NOM VARCHAR(255),
    PRENOM VARCHAR(255),
    SEXE BOOLEAN NOT NULL,
    OWNER_ID INTEGER
);            
ALTER TABLE PUBLIC.RECEVEUR ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RECEVEUR; 
INSERT INTO PUBLIC.RECEVEUR(ID, AGE, NOM, PRENOM, SEXE, OWNER_ID) VALUES
(1, 84, 'Bardot', 'Brigitte', TRUE, NULL);            
CREATE MEMORY TABLE PUBLIC.UTILISATEUR(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2DD5252D_AA42_4D16_AEAE_08F481A3AE6E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_2DD5252D_AA42_4D16_AEAE_08F481A3AE6E,
    IDPROFILASSOCIE INTEGER NOT NULL,
    MAIL VARCHAR(255),
    MDP VARCHAR(255)
);
ALTER TABLE PUBLIC.UTILISATEUR ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);             
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.UTILISATEUR;              
INSERT INTO PUBLIC.UTILISATEUR(ID, IDPROFILASSOCIE, MAIL, MDP) VALUES
(1, 1, 'mail', 'mdp'),
(2, 1, NULL, NULL);               
ALTER TABLE PUBLIC.RECEVEUR ADD CONSTRAINT PUBLIC.FKGWPFVR3GN4RN7NAO16R8ERQIP FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.CENTRE(ID) NOCHECK;      
ALTER TABLE PUBLIC.RDV ADD CONSTRAINT PUBLIC.FK7YIGSOAFSX9QJ8MMO61JIPPV2 FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.CENTRE(ID) NOCHECK;           
ALTER TABLE PUBLIC.DONNEUR ADD CONSTRAINT PUBLIC.FKJ8QTRC1588GU5L4KUXRK4EFB3 FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.CENTRE(ID) NOCHECK;       
ALTER TABLE PUBLIC.MEDECIN ADD CONSTRAINT PUBLIC.FK30SJW8WA1WKDAW1QTS0PNOFW4 FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.CENTRE(ID) NOCHECK;       
