SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS SA SALT '99037a41e155a5f9' HASH 'b61d7960e44c896b31dfe0ae4a762f20cfdb923198479addb039e1eb1b98a698' ADMIN;            
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4B94E0EF_3A9A_4084_B58F_2C405BBA00D8 START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_17993BB1_9DB4_4F35_99A0_0EADD1A63B94 START WITH 3 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FED001F0_76E2_4EC9_8BB3_022F3B7E1BF6 START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EA6F5AF7_7C7D_414C_87B1_FDD4F5A7CE44 START WITH 4 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3C6EDB3F_105C_4236_80A8_155A8E5F513E START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FB8FED4D_75B7_4BAE_896D_B5D42C700FA3 START WITH 2 BELONGS_TO_TABLE;     
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C6DD8197_6091_46E7_90F5_56D71B1959A3 START WITH 2 BELONGS_TO_TABLE;     
CREATE MEMORY TABLE PUBLIC.CENTRE(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3C6EDB3F_105C_4236_80A8_155A8E5F513E) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_3C6EDB3F_105C_4236_80A8_155A8E5F513E,
    ADRESSE VARCHAR(255),
    NOM VARCHAR(255),
    VILLE VARCHAR(255)
);
ALTER TABLE PUBLIC.CENTRE ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID);  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CENTRE;   
INSERT INTO PUBLIC.CENTRE(ID, ADRESSE, NOM, VILLE) VALUES
(1, '46 rue Schubert', 'Gaillard', 'Caen');          
CREATE MEMORY TABLE PUBLIC.DONNEUR(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_17993BB1_9DB4_4F35_99A0_0EADD1A63B94) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_17993BB1_9DB4_4F35_99A0_0EADD1A63B94,
    AGE INTEGER NOT NULL,
    ANTECEDENTS INTEGER,
    ATTENTE BOOLEAN NOT NULL,
    CHEVEUX INTEGER,
    DISPONIBILITE BOOLEAN NOT NULL,
    LOISIRS INTEGER,
    NOM VARCHAR(255),
    PEAU INTEGER,
    POIDS INTEGER NOT NULL,
    PRENOM VARCHAR(255),
    SEXE BOOLEAN NOT NULL,
    SIGNALE BOOLEAN NOT NULL,
    TAILLE INTEGER NOT NULL,
    YEUX INTEGER,
    OWNER_ID INTEGER
);             
ALTER TABLE PUBLIC.DONNEUR ADD CONSTRAINT PUBLIC.CONSTRAINT_9 PRIMARY KEY(ID); 
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.DONNEUR;  
INSERT INTO PUBLIC.DONNEUR(ID, AGE, ANTECEDENTS, ATTENTE, CHEVEUX, DISPONIBILITE, LOISIRS, NOM, PEAU, POIDS, PRENOM, SEXE, SIGNALE, TAILLE, YEUX, OWNER_ID) VALUES
(1, 26, 6, FALSE, 3, TRUE, 6, 'Martin', 1, 64, 'Thomas', FALSE, FALSE, 169, 3, NULL),
(2, 78, 7, FALSE, 0, TRUE, 8, 'Arnaud', 1, 50, 'Louis', FALSE, FALSE, 120, 5, 1);     
CREATE MEMORY TABLE PUBLIC.MEDECIN(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FB8FED4D_75B7_4BAE_896D_B5D42C700FA3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FB8FED4D_75B7_4BAE_896D_B5D42C700FA3,
    NOM VARCHAR(255),
    SEXE BOOLEAN NOT NULL,
    SPECIALISATION INTEGER,
    OWNER_ID INTEGER
);    
ALTER TABLE PUBLIC.MEDECIN ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.MEDECIN;  
INSERT INTO PUBLIC.MEDECIN(ID, NOM, SEXE, SPECIALISATION, OWNER_ID) VALUES
(1, 'Roche', TRUE, 0, 1);           
CREATE MEMORY TABLE PUBLIC.NOTIFICATION(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_4B94E0EF_3A9A_4084_B58F_2C405BBA00D8) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_4B94E0EF_3A9A_4084_B58F_2C405BBA00D8,
    STATU INTEGER,
    DONNEUR_ID INTEGER,
    RECEVEUR_ID INTEGER
);              
ALTER TABLE PUBLIC.NOTIFICATION ADD CONSTRAINT PUBLIC.CONSTRAINT_A PRIMARY KEY(ID);            
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.NOTIFICATION;             
INSERT INTO PUBLIC.NOTIFICATION(ID, STATU, DONNEUR_ID, RECEVEUR_ID) VALUES
(1, 0, 2, 1);       
CREATE MEMORY TABLE PUBLIC.RDV(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_C6DD8197_6091_46E7_90F5_56D71B1959A3) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_C6DD8197_6091_46E7_90F5_56D71B1959A3,
    HEURE INTEGER NOT NULL,
    JOUR INTEGER NOT NULL,
    MOIS INTEGER NOT NULL,
    DONNEUR_ID INTEGER,
    MEDECIN_ID INTEGER
);         
ALTER TABLE PUBLIC.RDV ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RDV;      
INSERT INTO PUBLIC.RDV(ID, HEURE, JOUR, MOIS, DONNEUR_ID, MEDECIN_ID) VALUES
(1, 15, 3, 12, 2, 1);             
CREATE MEMORY TABLE PUBLIC.RECEVEUR(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FED001F0_76E2_4EC9_8BB3_022F3B7E1BF6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FED001F0_76E2_4EC9_8BB3_022F3B7E1BF6,
    AGE INTEGER NOT NULL,
    NOM VARCHAR(255),
    PRENOM VARCHAR(255),
    SEXE BOOLEAN NOT NULL
);  
ALTER TABLE PUBLIC.RECEVEUR ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RECEVEUR; 
INSERT INTO PUBLIC.RECEVEUR(ID, AGE, NOM, PRENOM, SEXE) VALUES
(1, 48, 'Renard', 'Julie', TRUE);               
CREATE MEMORY TABLE PUBLIC.UTILISATEUR(
    ID INTEGER DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EA6F5AF7_7C7D_414C_87B1_FDD4F5A7CE44) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EA6F5AF7_7C7D_414C_87B1_FDD4F5A7CE44,
    IDPROFILASSOCIE INTEGER NOT NULL,
    ISRECEVEUR BOOLEAN NOT NULL,
    MAIL VARCHAR(255),
    MDP VARCHAR(255)
);               
ALTER TABLE PUBLIC.UTILISATEUR ADD CONSTRAINT PUBLIC.CONSTRAINT_5 PRIMARY KEY(ID);             
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.UTILISATEUR;              
INSERT INTO PUBLIC.UTILISATEUR(ID, IDPROFILASSOCIE, ISRECEVEUR, MAIL, MDP) VALUES
(1, 1, FALSE, 'tom', 'tommar'),
(2, 1, TRUE, 'jul', 'juju'),
(3, 2, FALSE, 'loar', 'loar');  
ALTER TABLE PUBLIC.NOTIFICATION ADD CONSTRAINT PUBLIC.FKAEXHYK31QAG3SF0C4LWV6DPC5 FOREIGN KEY(DONNEUR_ID) REFERENCES PUBLIC.DONNEUR(ID) NOCHECK;               
ALTER TABLE PUBLIC.RDV ADD CONSTRAINT PUBLIC.FKPCFVLYV97JF3TIWGBSQ2B71MR FOREIGN KEY(DONNEUR_ID) REFERENCES PUBLIC.DONNEUR(ID) NOCHECK;        
ALTER TABLE PUBLIC.RDV ADD CONSTRAINT PUBLIC.FKSJVIYMT7HVM6QQBR0P1HXL0T4 FOREIGN KEY(MEDECIN_ID) REFERENCES PUBLIC.MEDECIN(ID) NOCHECK;        
ALTER TABLE PUBLIC.DONNEUR ADD CONSTRAINT PUBLIC.FKJ8QTRC1588GU5L4KUXRK4EFB3 FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.CENTRE(ID) NOCHECK;       
ALTER TABLE PUBLIC.MEDECIN ADD CONSTRAINT PUBLIC.FK30SJW8WA1WKDAW1QTS0PNOFW4 FOREIGN KEY(OWNER_ID) REFERENCES PUBLIC.CENTRE(ID) NOCHECK;       
ALTER TABLE PUBLIC.NOTIFICATION ADD CONSTRAINT PUBLIC.FK5RB0RJT7ARPNL6OWNSJS6S5XP FOREIGN KEY(RECEVEUR_ID) REFERENCES PUBLIC.RECEVEUR(ID) NOCHECK;             
